GetBooksWeb/Areas/Admin/Controllers/OrderController.cs
using GetBooks.DataAccess.IRepository;
using GetBooks.Models;
using GetBooks.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace GetBooksWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = Roles.Admin)]
    public class OrderController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        public OrderController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult GetAll()
        {
            IEnumerable<Order> orders = Enumerable.Empty<Order>();
            orders = unitOfWork.Order.GetAll(includeProperties: "User");
            return Json(new { data = orders });
        }

        public IActionResult Get(int? id)
        {
            Order order = unitOfWork.Order.GetFirstOrDefault(x => x.Id == id);
            if (order == null)
            {
                return Json(new { found = false });
            }
            var items = unitOfWork.CartItem.GetAll(x => x.CartId == order.CartId);
            return Json(new { found = true, data = items , status=order.Status});
        }

        public IActionResult ChangeStatus(int? id, int status)
        {
            Order order = unitOfWork.Order.GetFirstOrDefault(x => x.Id == id);
            if (order == null)
            {
                return Json(new { success = false, message = "Order not found" });
            }
            order.Status = (OrderStatus)status;
            unitOfWork.Save();
            return Json(new { success = true, message = "Order status has changed" });
        }
    }
}

GetBooksWeb/Areas/Admin/Controllers/UserController.cs
using GetBooks.DataAccess.Data;
using GetBooks.Models.ViewModels;
using GetBooks.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GetBooksWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles=Roles.Admin)]
    public class UserController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly SignInManager<IdentityUser> signInManager;

        public UserController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager, SignInManager<IdentityUser> signInManager)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
            this.signInManager = signInManager;
        }

        public IActionResult Index()
        {
            List<UserVM> users = new List<UserVM>();
            foreach (var user in userManager.Users.ToList())
            {
                users.Add(new UserVM()
                {
                    Id = user.Id,
                    Email = user.Email,
                    Role = userManager.GetRolesAsync(user).GetAwaiter().GetResult().ToArray()[0],
                });
            }
            return View(users);
        }

        public IActionResult Edit(string? id)
        {
            IdentityUser user = userManager.Users.FirstOrDefault(u => u.Id == id);
            if (user != null)
            {
                UserVM uservm = new UserVM()
                {
                    Id = user.Id,
                    Email=user.Email,
                    Role = userManager.GetRolesAsync(user).GetAwaiter().GetResult().ToArray()[0],
                };
                UserEditVM userEditVM = new UserEditVM()
                {
                    UserVM = uservm,
                    RoleList = roleManager.Roles.Select(x => x.Name).Select(i => new SelectListItem
                    {
                        Text = i,
                        Value = i
                    })
                };
                return View(userEditVM);
            }
            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(UserEditVM uevm)
        {
            
            if (ModelState.IsValid)
            {
                IdentityUser user = userManager.FindByIdAsync(uevm.UserVM.Id).GetAwaiter().GetResult();
                if (user != null)
                {
                    if (uevm.UserVM.Email != user.Email)
                    {
                        var result = userManager.SetEmailAsync(user, uevm.UserVM.Email).GetAwaiter().GetResult();
                        if (!IsEditResultSuccesfull(result))
                        {
                            uevm.RoleList = roleManager.Roles.Select(x => x.Name).Select(i => new SelectListItem
                            {
                                Text = i,
                                Value = i
                            });
                            return View(uevm);
                        }
                    }

                    IList<string> userRoles = userManager.GetRolesAsync(user).GetAwaiter().GetResult();
                    
                    if (!userRoles.Contains(uevm.UserVM.Role))
                    {
                        userManager.RemoveFromRolesAsync(user, userRoles).GetAwaiter().GetResult();
                        var result = userManager.AddToRoleAsync(user, uevm.UserVM.Role).GetAwaiter().GetResult();
                        if (!IsEditResultSuccesfull(result))
                        {
                            uevm.RoleList = roleManager.Roles.Select(x => x.Name).Select(i => new SelectListItem
                            {
                                Text = i,
                                Value = i
                            });
                            return View(uevm);
                        }
                    }

                    if (uevm.NewPassword != null)
                    {
                        var token = userManager.GeneratePasswordResetTokenAsync(user).GetAwaiter().GetResult();
                        var result = userManager.ResetPasswordAsync(user, token, uevm.NewPassword).GetAwaiter().GetResult();
                        if (!IsEditResultSuccesfull(result))
                        {
                            uevm.RoleList = roleManager.Roles.Select(x => x.Name).Select(i => new SelectListItem
                            {
                                Text = i,
                                Value = i
                            });
                            return View(uevm);
                        }
                    }

                    TempData["success"] = "User updated succesfully";
                    return RedirectToAction(nameof(Edit), new {id = user.Id});
                }
                return NotFound();
            }
            uevm.NewPassword = null;
            return View(uevm);
        }
        
        private bool IsEditResultSuccesfull(IdentityResult result)
        {
            if (!result.Succeeded)
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
                TempData["error"] = "User could not updated";
                return false;
            }
            return true;
        }

        [HttpDelete]
        public IActionResult Delete(string? userId)
        {
            IdentityUser user = userManager.FindByIdAsync(userId).GetAwaiter().GetResult();
            if (user != null)
            {
                var result = userManager.DeleteAsync(user).GetAwaiter().GetResult();
                string message = result.Succeeded ? "User has deleted succesfully" : "User couldn't deleted";
                return Json(new { success = result.Succeeded, message=message});

            }
            return Json(new { success = false, message = "User couldn't found" });
        }
    
        
    }
}

GetBooksWeb/Areas/Shop/Controllers/BookController.cs
using GetBooks.DataAccess.IRepository;
using GetBooks.Models;
using GetBooksWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GetBooksWeb.Areas.Shop.Controllers
{
    [Area("Shop")]
    public class BookController : Controller
    {
        private readonly ILogger<BookController> _logger;

        private readonly IUnitOfWork unitOfWork;
        public BookController(ILogger<BookController> logger, IUnitOfWork unitOfWork)
        {
            _logger = logger;
            this.unitOfWork = unitOfWork;

        }
        public IActionResult Index()
        {
            IEnumerable<Book> books = unitOfWork.Book.GetAll();
            return View(books);
        }

        public IActionResult Details(int bookId)
        {
            Book book = unitOfWork.Book.GetFirstOrDefault(u => u.Id == bookId);
            return View(book);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GetBooksWeb/ViewComponents/ShoppingCartViewComponent.cs
using GetBooks.DataAccess.IRepository;
using GetBooks.Models;
using GetBooks.Utility;
using Microsoft.AspNetCore.Mvc;

namespace GetBooksWeb.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IUnitOfWork unitOfWork;
        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            string userId = IdentityUtility.GetUserId(User.Identity);
            if (userId == null)
            {
                HttpContext.Session.Clear();
                return View(0);
            }
            int? itemCountInSession = HttpContext.Session.GetInt32(Statics.CartItemCount);
            if (itemCountInSession == null)
            {
                Cart cart = unitOfWork.Cart.GetFirstOrDefault(x => x.UserId == userId && x.Status == CartStatus.InShopping);
                if (cart == null)
                {
                    HttpContext.Session.SetInt32(Statics.CartItemCount, 0);
                    return View(0);
                }
                else
                {
                    int itemCount = unitOfWork.CartItemTemp.GetAll(x => x.CartId == cart.Id).ToList().Count;
                    HttpContext.Session.SetInt32(Statics.CartItemCount, itemCount);
                    return View(itemCount);
                }
            }
            else
            {
                return View(itemCountInSession);
            }
        }
    }
}

GetBooksWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using GetBooks.Utility
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GetBooksWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/morphTheme.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GetBooksWeb.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css"

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
           <div class="container-fluid">
              <a class="navbar-brand pe-2" asp-area="Shop" asp-controller="Book" asp-action="Index" >GetBooks</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarColor01">
                 <ul class="navbar-nav me-auto">
                    <li class="nav-item pe-2">
                       <a class="nav-link active" asp-area="Shop" asp-controller="Book" asp-action="Index">Home
                            <span class="visually-hidden">(current)</span>
                       </a>
                    </li>
                    @if (User.IsInRole(Roles.Admin))
                    {
                        <li class="nav-item dropdown pe-2">
                            <label class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin Panel</label>
                            <div class="dropdown-menu">
                                <h5 class="dropdown-header">Product Management</h5>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Book" asp-action="Index">Book Management</a>
                                <div class="dropdown-divider"></div>
                                <h5 class="dropdown-header">User Management</h5>
                                <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create User</a> 
                                <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">Users</a>
                                <div class="dropdown-divider"></div>
                                <h5 class="dropdown-header">Order Management</h5>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Order" asp-action="Index">Orders</a>
                            </div>
                        </li>
                    }
                    @if (User.Identity.IsAuthenticated){
                        <li class="nav-item pe-2">
                            <a class="nav-link active" asp-area="Customer" asp-controller="Cart" asp-action="Summary">
                               <i class="bi bi-cart"></i> <span id="cartItemCount">@await Component.InvokeAsync("ShoppingCart")</span>
                            </a>
                        </li>
                        <li class="nav-item pe-2">
                            <a class="nav-link active" asp-area="Customer" asp-controller="Order" asp-action="Index"><i class="bi bi-clock-history"></i> Order History</a>
                        </li>
                    }
                    
                 </ul>
                 <partial name="_LoginPartial" />
              </div>
           </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_NotificationPartial" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="bottom:5px;position: fixed; width:100%;">
        <div class="container text-">
            &copy; 2022 - GetBooks
        </div>
    </footer>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GetBooksWeb/Views/Shared/_NotificationPartial.cshtml
@if (TempData["success"] != null){
	<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.success('@TempData["success"]');
	</script>
}
@if (TempData["error"] != null){
	<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.error('@TempData["error"]');
	</script>
}